@extends('layouts.dosen')
@section('title','Verifikasi Nilai Kaprodi')
@section('content')
<div class="card shadow-sm mb-4"><div class="card-body"><h4>Verifikasi Nilai</h4><p class="text-muted mb-2">Periksa nilai dosen sebelum diterbitkan BAAK.</p><div class="small"><span class="text-muted">Program studi yang Anda verifikasi:</span> <strong>{{ $programStudiDipimpin->pluck('nama')->join(', ') ?: 'Belum ditetapkan' }}</strong></div></div></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Mata Kuliah</th><th>Kelas / TA</th><th>Penginput</th><th>Diajukan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($submissions as $item)<tr><td><b>{{$item->jadwal?->kurikulum?->mataKuliah?->nama??'-'}}</b></td><td>{{jenis_kelas_label($item->jadwal?->jenis_kelas??'Reguler')}}<small class="d-block text-muted">{{$item->jadwal?->tahunAjaran?->nama}}</small></td><td>{{$item->submitter?->nama??'-'}}</td><td>{{optional($item->submitted_at)->format('d/m/Y H:i')}}</td><td><span class="badge bg-label-{{['submitted'=>'warning','approved'=>'success','revision'=>'danger'][$item->status]??'secondary'}}">{{['submitted'=>'Menunggu ACC','approved'=>'Disetujui','revision'=>'Perlu revisi'][$item->status]??$item->status}}</span>@if($item->review_note)<small class="d-block text-danger">{{$item->review_note}}</small>@endif</td><td>@if($item->status==='submitted')<form class="d-inline" method="POST" action="{{route('dosen.kaprodi.nilai.approve',$item)}}">@csrf<button class="btn btn-sm btn-success" onclick="return confirm('Setujui nilai?')">ACC</button></form><form class="d-flex gap-1 mt-1" method="POST" action="{{route('dosen.kaprodi.nilai.revision',$item)}}">@csrf<input class="form-control form-control-sm" name="review_note" required placeholder="Catatan revisi"><button class="btn btn-sm btn-outline-danger">Revisi</button></form>@else<span class="small text-muted">Sudah diproses</span>@endif</td></tr>@empty<tr><td colspan="6" class="text-center py-5">Belum ada pengajuan nilai.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{$submissions->links()}}</div></div>
<div class="card shadow-sm mt-3"><div class="card-body"><h6>Rincian untuk diperiksa</h6><div class="d-flex flex-wrap gap-2">@foreach($submissions as $item)<a class="btn btn-sm btn-outline-primary" href="{{route('dosen.kaprodi.nilai.show',$item)}}">Periksa {{$item->jadwal?->kurikulum?->mataKuliah?->nama??'Nilai'}}</a>@endforeach</div></div></div>
@endsection
